# ABOUTME: Pre-selected board configuration for Inkplate 10 (ESP32).
# ABOUTME: Passed to CMake via -DARDUINO_BOARD_OPTIONS_FILE to avoid manual board selection.
set(ARDUINO_BOARD "Inkplate 10 (ESP32) [Inkplate.Inkplate10]")
set(ARDUINO_INKPLATE_INKPLATE10_MENU_PSRAM_ENABLED TRUE)
set(ARDUINO_INKPLATE_INKPLATE10_MENU_PARTITIONSCHEME_HUGE_APP TRUE)
set(ARDUINO_INKPLATE_INKPLATE10_MENU_CPUFREQ_240 TRUE)
